name: CI

on:
  push:
    branches:
      - "**"

jobs:

  test:
    permissions:
      contents: 'read'
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        version:
          - 1.19.4
          - 1.20rc2

    steps:
      - uses: actions/checkout@v3.1.0

      - name: Vet
        run: |
          docker run \
            --rm \
            --volume "$(pwd):/src" \
            --workdir /src \
            golang:${{ matrix.version }}-bullseye go vet ./...

      - name: Test
        run: |
          docker run \
            --rm \
            --volume "$(pwd):/src" \
            --workdir /src \
            golang:${{ matrix.version }}-bullseye go test -shuffle on -count=10 -race ./...
